blogproject/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # 将主页视图函数改写成类函数
    url(r'^$', views.IndexView.as_view(), name='index'),

    # 将 category 视图函数改写为类视图
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='Category'),
    # url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),

    # 将archives视图函数改写为类函数
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archivesView.as_view(), name='archives'),

    url(r'^post/(?P<pk>[0-9]+)$', views.detail, name='detail'),
    # url(r'^post/(?P<pk>[0-9]+)$', views.PostDetailView.as_view(), name='detail'),

    # url(r'^tag/(?P<pk>[0-9]+)/$', views.tags, name='tag')
    url(r'^tag/(?P<pk>[0-9]+)/$', views.Tagview.as_view(), name='tag'),

    # 搜索
    # url(r'^search/$', views.search, name='search')
]

blogproject/blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),

    url(r'^all/rss/', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

blogproject/comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blogproject/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags

# Create your models here.
'''
分类
'''


class Category(models.Model):
    '''
    Django要求模型必须继承models.Model类。
    Categoty只需要一个简单的分类名name就可以了
    Charfield制定了分类名name的数据类型，Charfield是字符类型
    Charfield的max_lengh参数指定了其最大的长度，超过这个长度的分类名不能被存入数据库
    '''
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_category_url(self):
        return reverse('blog:Category', kwargs={'pk': self.pk})


'''
标签
'''


class Tags(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_tag_url(self):
        return reverse('blog:tag', kwargs={'pk': self.pk})


'''
文章
'''


class Post(models.Model):
    title = models.CharField(max_length=70)

    # 文章正文，我们使用TextField。
    # 存储短比较短的内容我们可以用CharField，但对于比较长的内容我们应该用TextField
    body = models.TextField()

    # 这两个列表示文章的创建时间和修改时间，存储时间用DateTimeField类型
    creatd_time = models.DateTimeField()
    modfied_time = models.DateTimeField()

    # 文章摘要，可以没有文章摘要，但默认情况下，CharField要求我们必须存入数据，不然会报错
    # 指定Charfield的blank = True 参数值后就允许空值了
    excerpt = models.CharField(max_length=200, blank=True)

    # 分类和标签，分类和标签的模型在下面另外定义。
    # 我们要在这里把文章对应的数据库和分类，标签对应的数据库关联了起来，但是关联的形式稍微有点不同
    # 我们规定一篇文章只有一个分类，但是一个分类下面有多篇文章，所有我们使用的是ForeignKey，即一对多的关联方式
    # 而对标签来说，一篇文章可以有多个标签，同一个标签下面也有多个文章，所有我们使用的是ManyToManyField，表明这个是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此标签tags，指定了blank=True
    categoty = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tags, blank=True)

    # 文章作者
    # django.contrib.auth是Django内置的应用，专门用于处理网站用户的登录注册等流程，User是Django为我们写好的用户模型。
    # 这里我们用ForeignKey把文章和User关联起来
    # 因为我们规定一篇文章只有一个作者，而一个作者可能有多篇文章，因此这个是一对多的关联关系。
    author = models.ForeignKey(User)

    # 阅读数
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def get_archives_url(self):
        return reverse('blog:archives', kwargs={'year': self.creatd_time.year, 'month': self.creatd_time.month})
        # { % url'blog:archives' date.year date.month %}

    class Meta:
        ordering = ['creatd_time', 'title']

    # 统计阅读数
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 重写save方法，为了从正文字段摘取前N个字符保存到摘要字段。
    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先渲染一个Markdown类，用于渲染body文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite'
            ])
            # 先将Markdown文本渲染成HTML文本
            # strip_tags去掉HTML文本的全部HTML标签
            # 从文本前摘取前54个字符赋给excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 调用父类的save方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

blogproject/comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible

# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blogproject/blog/views.py
from django.shortcuts import render, get_object_or_404
# Create your views here.

from django.http import HttpResponse
from django.shortcuts import render
from .models import Post, Category, Tags
from comments.forms import CommentForm

# 将index视图函数改写成类函数,引入ListView的方法
from django.views.generic import ListView, DetailView

# 搜索
from django.db.models import Q

# 引入Markdown模块
'''
Markdown 是一种 HTML 文本标记语言，只要遵循它约定的语法格式，Markdown 的渲染器就能够把我们写的文章转换为标准的 HTML 文档，
从而让我们的文章呈现更加丰富的格式，例如标题、列表、代码块等等 HTML 元素。由于 Markdown 语法简单直观
'''
import markdown


# 将主页视图函数改写成类函数
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 2

    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


# 主页视图
def index(request):
    post_list = Post.objects.all().order_by('-creatd_time')
    return render(request, 'blog/index.html', context={
        'post_list': post_list
    })


# 详情页视图
def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # 评论数+1
    post.increase_views()

    # 文章内容进行markdown处理
    post.body = markdown.markdown(post.body, extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])

    form = CommentForm()
    # 获取这篇Post下所有评论
    comment_list = post.comment_set.all()
    for cl in comment_list:
        cl.text = markdown.markdown(cl.text, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])

    # 将文章、表单以及文章下的评论列表作为模板变量传给detail.html模板，以便渲染相应数据
    context = {
        'post': post,
        'form': form,
        'comment_list': comment_list,
    }

    return render(request, 'blog/detail.html', context=context)


# 详情页视图改写成类函数
class PostDetailView(DetailView):
    # 这些属性的含义和ListView一样
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 编写get方法的目的是因为每当文章被访问一次，就得将文章的阅读量+1
        # get方法返回的是一个HttpResponse实例
        # 之所以需要调用父类的get方法，是因为只有当get方法被调用后，
        # 才会有self.object属性，其值为Post模型实例，即被访问的文章post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读数 + 1
        # 注意self.object的值就是被访问的文章post
        self.object.increase_views()

        # 视图必须返回一个HttpResponese对象
        return response

    def get_object(self, queryset=None):
        # 编写get_object方法的目的是因为需要对post的body值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.markdown(post.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        # 编写get_context_data的目的是因为除了将post传递给模板外<DetailView已经帮我们完成了>
        # 还有将表单评论，post下的评论列表传递给模板
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list,
        })
        return context


# 归档视图
def archives(request, year, month):
    post_list = Post.objects.filter(
        creatd_time__year=year,
        creatd_time__month=month,
    ).order_by(
        '-creatd_time'
    )
    return render(request, 'blog/index.html', context={'post_list': post_list})


# 归档视图改写成类函数
class archivesView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(archivesView, self).get_queryset().filter(creatd_time__year=year, creatd_time__month=month)


# 分类页视图
def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(categoty=cate).order_by('-creatd_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


# 将分类页视图改为类函数
class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


# 标签页视图
def tags(request, pk):
    tag = get_object_or_404(Tags, pk=pk)
    post_list = Post.objects.filter(tags=tag).order_by('-creatd_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


class Tagview(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 2

    def get_queryset(self):
        tag = get_object_or_404(Tags, pk=self.kwargs.get('pk'))
        return super(Tagview, self).get_queryset().filter(tags=tag)

    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。

blogproject/templates/blog/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="static/blog/css/bootstrap.min.css">
		<link rel="stylesheet" href="static/blog/css/ionicons.min.css">
		<link rel="stylesheet" href="static/blog/css/pace.css">
	    <link rel="stylesheet" href="static/blog/css/custom.css">

	    <!-- js -->
	    <script src="static/blog/js/jquery-2.1.3.min.js"></script>
	    <script src="static/blog/js/bootstrap.min.js"></script>
	    <script src="static/blog/js/pace.min.js"></script>
	    <script src="static/blog/js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="static/img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="static/blog/js/script.js"></script>
		
	</body>
</html>

blogproject/templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.categoty.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="{{ post.creatd_time }}">{{ post.creatd_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            <span class="views-count"><a href="#">
                    Tags:
                    {% for tag in post.tags.all %}
                        <a href="#">{{ tag.name }}</a>
                    {% endfor %}
                </a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{ post.body|safe }}
    </div>
</article>
<section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>

    <!--{#    <form action="#" method="post" class="comment-form">#}-->
    <!--{#        <div class="row">#}-->
    <!--{#            <div class="col-md-4">#}-->
    <!--{#                <label for="id_name">名字：</label>#}-->
    <!--{#                <input type="text" id="id_name" name="name" required>#}-->
    <!--{#            </div>#}-->
    <!--{#            <div class="col-md-4">#}-->
    <!--{#                <label for="id_email">邮箱：</label>#}-->
    <!--{#                <input type="email" id="id_email" name="email" required>#}-->
    <!--{#            </div>#}-->
    <!--{#            <div class="col-md-4">#}-->
    <!--{#                <label for="id_url">网址：</label>#}-->
    <!--{#                <input type="text" id="id_url" name="url">#}-->
    <!--{#            </div>#}-->
    <!--{#            <div class="col-md-12">#}-->
    <!--{#                <label for="id_comment">评论：</label>#}-->
    <!--{#                <textarea name="comment" id="id_comment" required></textarea>#}-->
    <!--{#                <button type="submit" class="comment-btn">发表</button>#}-->
    <!--{#            </div>#}-->
    <!--{#        </div>    &lt;!&ndash; row &ndash;&gt;#}-->
    <!--{#    </form>#}-->
    <!--{#    评论#}-->
    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="{{ form.name.id_for_label }}">名字：</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.url.id_for_label }}">网址：</label>
                {{ form.url }}
                {{ form.url.errors }}
            </div>
            <div class="col-md-12">
                <label for="{{ form.text.id_for_label }}">评论：</label>
                {{ form.text }}
                {{ form.text.errors }}
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div>
    </form>

    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论
        </h3>
        <ul class="comment-list list-unstyled">

            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="nickname">{{ comment.name }}</span>
                <time class="submit-date"
                      datetime="{{ comment.created_time }}">{{ comment.created_time }}
                </time>
                <div class="text">
                    {{ comment.text|safe }}
                </div>
            </li>
            {% empty %}
            没有评论
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock main %}